menu_options:
    - key: inbound_volume
      label: 搬入量予測
    - key: balance_management_table
      label: 工場収支モニタリング表

required_files:
    inbound_volume: [receive]
    balance_management_table: [shipping]
