menu_options:
    - key: inbound_volume
      label: 搬入量予測AI
      handler: render_import_volume

    - key: balance_management_table
      label: 現在数量モニタリング
      handler: factory_manage_controller

    - key: inbound_outbound_records
      label: 搬出入収支表
      handler: render_inbound_outbound_records

    - key: sanbo_navi
      label: 参謀ナビ
      handler: render_sanbo_navi

required_files:
    inbound_volume: [receive]
    balance_management_table: [shipping]
    inbound_outbound_records: [receive, shipping]
