repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0  # 使用するBlackのバージョン
    hooks:
      - id: black
        language_version: python3  # Python3を指定

  - repo: https://github.com/pre-commit/mirrors-ruff
    rev: v0.0.118  # 使用するRuffのバージョン
    hooks:
      - id: ruff
        language_version: python3
