[tool.black]
line-length = 88
target-version = ["py310"]
skip-string-normalization = false  # ダブルクォート統一（false 推奨）

exclude = '''
/(
    app/__archive__(/|$)
  | \.git
  | \.mypy_cache
  | \.ruff_cache
  | __pycache__
)/
'''
[tool.ruff]
line-length = 88
target-version = "py310"
fix = true
select = [
    "E",   # pycodestyle (PEP8)
    "F",   # pyflakes
    "B",   # flake8-bugbear
    "I",   # isort
    "UP",  # pyupgrade
    "C90", # mccabe（複雑度チェック）
]
ignore = [
    "E501",  # 長すぎる行 → blackに任せる
    "F401",  # 未使用import → 開発中は許容
    "F841",  # 未使用変数 → デバッグ途中でも許容
]

[tool.ruff.format]
quote-style = "double"

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = 3.10
check_untyped_defs = true
ignore_missing_imports = true
disallow_untyped_defs = false
warn_unused_ignores = true
no_implicit_optional = true
strict_optional = true

[tool.mypy-report]
# mypyのレポート出力用（任意）
# html_report = "mypy_report"
# files = ["app"]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
