# ✅ 共通定義（master schema）
column_types:
    shipping: &shipping_schema
        業者CD: int
        業者名: str
        金額: int
        正味重量: int
        伝票日付: datetime
        品名: str

    yard: &yard_schema
        種類名: str
        数量: int
        正味重量: int
        伝票日付: datetime
        品名: str

    receive: &receive_schema
        金額: int
        受入番号: int
        集計項目CD: int
        数量: int
        正味重量: int
        単位名: str
        単価: int
        伝票区分名: str
        伝票日付: datetime
        品名: str
        品名CD: int

# ✅ 各用途別で再利用（アンカー参照）
average_sheet:
    receive:
        金額: float
        受入番号: int
        集計項目CD: int
        正味重量: int
        単位名: str
        伝票区分名: str
        伝票日付: datetime
        品名: str
        品名CD: int

factory_report:
    shipping:
        業者CD: int
        正味重量: int
        品名: str
    yard:
        正味重量: int
        品名: str

balance_sheet:
    shipping: *shipping_schema
    yard: *yard_schema
    receive: *receive_schema

block_unit_price:
    shipping:
        業者CD: int
        業者名: str
        正味重量: int
        数量: int
        単価: float
        明細備考: str
        伝票日付: datetime
        品名: str
        単位名: str

management_sheet:
    shipping: *shipping_schema
    yard: *yard_schema
    receive:
        - *receive_schema

# 工場管理系
balance_management_table:
    shipping:
        伝票日付: datetime
        業者CD: int
        業者名: str
        取引先CD: str
        品名CD: int
        単位CD: int
        車種CD: int
        運搬業者CD: int
        種類CD: int
        正味重量: int
        金額: float
    master:
        大項目: str
        中項目: str
        業者CD: int
        取引先CD: str
        品名CD: int
        単位CD: int
        車種CD: int
        運搬業者CD: int
        種類CD: int

inbound_volume:
    receive:
        伝票日付: datetime
        正味重量: int
        品名: str
