average_sheet:
    receive:
        - 金額
        - 受入番号
        - 集計項目CD
        - 正味重量
        - 単位名
        - 伝票区分名
        - 伝票日付
        - 品名
        - 品名CD

factory_report:
    shipping:
        - 運搬業者名
        - 業者CD
        - 業者名
        - 現場名
        - 正味重量
        - 伝票日付
        - 品名
    yard:
        - 種類名
        - 正味重量
        - 伝票日付
        - 品名

balance_sheet:
    shipping:
        - 業者CD
        - 業者名
        - 金額
        - 正味重量
        - 品名

    yard:
        - 種類名
        - 数量
        - 正味重量
        - 品名

    receive:
        - 金額
        - 受入番号
        - 数量
        - 正味重量
        - 単位名
        - 単価
        - 伝票区分名
        - 品名
        - 伝票日付
