FROM python:3.10-slim

WORKDIR /work

# 必要パッケージ追加（日本語フォント・git・make・pkill用のprocps）
RUN apt-get update && \
    apt-get install -y \
    fonts-noto-cjk \
    fonts-noto \
    git \
    make \
    procps && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --no-cache-dir \
    black \
    ruff \
    isort \
    pre-commit

EXPOSE 8503

CMD ["streamlit", "run", "app/app.py", "--server.port=8503", "--server.address=0.0.0.0", "--server.headless=true", "--server.enableCORS=false"]
