FROM python:3.10-slim

WORKDIR /work

RUN apt-get update && \
    apt-get install -y fonts-noto-cjk fonts-noto git && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# コード取り込み
COPY ./app /work/app

EXPOSE 8502

CMD ["streamlit", "run", "app/app.py", "--server.port=8502", "--server.address=0.0.0.0", "--server.headless=true", "--server.enableCORS=false"]
