version: '3.8'

services:
  app:
    container_name: sanbou_staging
    build:
      context: ../
      dockerfile: docker/Dockerfile.staging
    working_dir: /work
    ports:
      - "8502:8502"
    environment:
      - APP_ENV=staging
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/work/app

    command:
      - streamlit
      - run
      - app/app.py
      - --server.port=8502
      - --server.address=0.0.0.0
      - --server.headless=true
      - --server.enableCORS=false
