version: '3'
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - '8503:8501'
    volumes:
      - ../:/work
      - ~/.ssh:/root/.ssh #git用
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/work/app
      - APP_ENV=dev
    working_dir: /work
    command: streamlit run app/app.py --server.port=8501 --server.address=0.0.0.0
