services:
  app:
    container_name: sanbou_prod
    build:
      context: ../
      dockerfile: docker/Dockerfile.prod
    working_dir: /work
    ports:
      - "8501:8501"
    environment:
      - APP_ENV=prod
      - PYTHONUNBUFFERED=1
      # - PYTHONPATH=/work/app
      # - BASE_DIR=/work/app
    env_file:
      - ../.env   # ← GITHUB_TOKEN や REPO_TAG, REPO_URL をここから読み込む
    restart: unless-stopped
    command:
      - streamlit
      - run
      # - app/app.py
      - app.py
      - --server.port=8501
      - --server.address=0.0.0.0
      - --server.headless=true
      - --server.enableCORS=false
