services:
  app:
    container_name: sanbou_prod
    build:
      context: ../
      dockerfile: docker/Dockerfile.prod
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        REPO_TAG: ${REPO_TAG}
        REPO_URL: ${REPO_URL}
    working_dir: /work
    ports:
      - "8501:8501"
    environment:
      - APP_ENV=prod
      - PYTHONUNBUFFERED=1
    env_file:
      - ../.env
    restart: unless-stopped
    command:
      - streamlit
      - run
      - app/app.py
      - --server.port=8501
      - --server.address=0.0.0.0
      - --server.headless=true
      - --server.enableCORS=false
