services:
  ragapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./config:/app/config
      - ./local_data:/app/local_data   # ← ✅これが重要！
    env_file:
      - ./config/.env
    environment:
      - PYTHONPATH=/app
