services:
  app:
    container_name: sanbou_prod
    build:
      context: ../
      dockerfile: docker/Dockerfile.prod
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        REPO_TAG: ${REPO_TAG}
        REPO_URL: ${REPO_URL}
    working_dir: /work
    ports:
      - "8502:8501"
    environment:
      - APP_ENV=${APP_ENV}
      - PYTHONUNBUFFERED=1
    env_file:
      - ../.env.staging
    restart: unless-stopped
