version: '3.8'

services:
  app:
    container_name: sanbou_dev
    build:
      context:  ${PWD}/..
      dockerfile: docker/Dockerfile.dev
    working_dir: /work
    volumes:
      - .:/work
    ports:
      - "8503:8503"
    environment:
      - APP_ENV=dev
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/work/app
    command:
      - streamlit
      - run
      - app/app.py
      - --server.port=8503
      - --server.address=0.0.0.0
      - --server.headless=true
      - --server.enableCORS=false
