receive:
    key: receive
    df: df_receive
    label: 受入一覧
    date_column: 伝票日付
yard:
    key : yard
    df : df_yard
    label: ヤード一覧
    date_column: 伝票日付
shipping:
    key : shipping
    df : df_shipping
    label : 出荷一覧
    date_column : 伝票日付
