average_sheet:
    receive:
        金額: float
        受入番号: int
        集計項目CD: int
        正味重量: int
        単位名: str
        伝票区分名: str
        伝票日付: datetime
        品名: str
        品名CD: int

factory_report:
    shipping:
        業者CD: str
        品名: str
        正味重量: int
    yard:
        品名: str
        正味重量: int
