# config/main_paths.yaml

# 📄 CSVファイル関連パス
csv:
    receive_header_definition: 'config/input_header_info.csv' # 種別判定用ヘッダー
    required_columns_definition: 'config/required_columns_definition.csv' # 必須カラムの定義
    expected_dtypes: 'config/expected_dtypes.json' # データ型の期待定義

# # excelテンプレートパス
# excel:
#     manage_template_path: 'data/master/abc_average_write_targets.csv'

# 📁 ディレクトリ構成
directories:
    output: 'data/output' # 出力結果の保存先
    master_data: 'data/master' # マスターCSVの格納場所
    template: 'data/template'
    temp: 'data/temp' # 一時ファイル格納

# 📜 ログ設定
logs:
    app: 'logs/app.log'
    error: 'logs/error.log'

# yamlパス
config_files:
    app_config: 'config/app_config.yaml'
    expected_dtypes: 'config/expected_dtypes.yaml'
    page_config: 'config/page_config.yaml'
    templates_config: 'config/templates_config.yaml'
    csv_sources_config: 'config/csv_sources_config.yaml'
    required_columns_definition: 'config/required_columns_definition.yaml'
    csv_type_signatures: 'config/csv_type_signatures.yaml'
