average_sheet:
    receive:
        - 金額
        - 受入番号
        - 集計項目CD
        - 正味重量
        - 単位名
        - 伝票区分名
        - 伝票日付
        - 品名
        - 品名CD

factory_report:
    shipping:
        - 業者CD
        - 品名
        - 正味重量
    yard:
        - 品名
        - 正味重量
