# テンプレートごとの構成と説明
factory_report:
    key: factory_report
    label: 工場日報
    description: ヤードと出荷データをもとに、工場内の稼働日報を出力します。
    required_files: [yard, shipping]
    master_csv_path:
        shobun: data/master/factory_report_shobun_map.csv
        yuuka: data/master/factory_report_yuuka_map.csv
        yard: data/master/factory_report_yard_map.csv
    template_excel_path: data/templates/factory_report.xlsx

balance_sheet:
    key: balance_sheet
    label: 工場搬出入収支表
    description: 受入・ヤード・出荷一覧から収支表を自動集計します。
    required_files: [receive, yard, shipping]

average_sheet:
    key: average_sheet
    label: 集計項目平均表
    description: 受入データをABC分類し、各品目の平均値を算出して出力します。
    required_files: [receive]
    master_csv_path: data/master/average_sheet_map.csv
    template_excel_path: data/templates/average_sheet.xlsx

management_sheet:
    key: management_sheet
    label: 管理票
    description: 受入・ヤード・出荷の一覧を使って管理用の帳票を出力します。
    required_files: [receive, yard, shipping]
